server:
  port: 7920

spring:
  application:
    name: eat-well
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/eatwell?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=Convert_To_Null&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456789

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

eat-well:
  path: /Users/lahmwang/EatWellFoodDelivery/imgs/